In [8]:
import pandas as pd

df = pd.read_csv('C:/Users/phpunsal/Documents/Data_Analytics/FTSE_Data/data/FTSE100.csv')

df.head()

,Company,Ticker,Sector,Mid-price (p),Change,Our view,Brokers,Strong Buy,Buy,Neutral,Sell,Strong Sell,Recommendation
0,3i,III,Financial Services,"1,099.50",0.0171,Hold,5,NaN,4,1,0,0,Buy
1,Admiral Group,ADM,Nonlife Insurance,"2,115.00",-0.42%,Hold,18,NaN,2,6,7,3,Underweight
2,Anglo American plc,AAL,Mining,"1,744.00",0.0154,Hold,24,NaN,15,6,2,0,Buy
3,Antofagasta,ANTO,Mining,848.2,0.0326,Hold,21,NaN,8,9,3,0,Overweight
4,Ashtead Group,AHT,Support Services,"2,207.00",0.0347,Buy,17,NaN,12,5,0,0,Buy

In [9]:
# this tells me that, other than Strong Buy, none of the columns have NaN values. There is also 101 rows, when there should be 100
#Mid-price and Change entries are also strings and will need to be converted
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Company         101 non-null    object
 1   Ticker          101 non-null    object
 2   Sector          101 non-null    object
 3   Mid-price (p)   101 non-null    object
 4   Change          101 non-null    object
 5   Our view        101 non-null    object
 6   Brokers         101 non-null    int64
 7   Strong Buy      0 non-null      float64
 8   Buy             101 non-null    int64
 9   Neutral         101 non-null    int64
 10  Sell            101 non-null    int64
 11  Strong Sell     101 non-null    int64
 12  Recommendation  101 non-null    object
dtypes: float64(1), int64(5), object(7)
memory usage: 10.4+ KB

In [10]:
# this shows me that Royal Dutch Shell has a duplicate entry
df.Company.value_counts()

Company
Royal Dutch Shell       2
Ocado                   1
Rolls-Royce Holdings    1
Rightmove               1
Rio Tinto Group         1
                       ..
Evraz                   1
Direct Line Group       1
Diageo                  1
DCC plc                 1
WPP plc                 1
Name: count, Length: 100, dtype: int64

In [11]:
# i will therefore drop the Strong Buy column and remove one of the Royal Dutch Shell entries
clean_df = df.copy()
clean_df = clean_df.drop('Strong Buy', axis=1)[clean_df.Ticker!='RDSA']

clean_df

,Company,Ticker,Sector,Mid-price (p),Change,Our view,Brokers,Buy,Neutral,Sell,Strong Sell,Recommendation
0,3i,III,Financial Services,"1,099.50",0.0171,Hold,5,4,1,0,0,Buy
1,Admiral Group,ADM,Nonlife Insurance,"2,115.00",-0.42%,Hold,18,2,6,7,3,Underweight
2,Anglo American plc,AAL,Mining,"1,744.00",0.0154,Hold,24,15,6,2,0,Buy
3,Antofagasta,ANTO,Mining,848.2,0.0326,Hold,21,8,9,3,0,Overweight
4,Ashtead Group,AHT,Support Services,"2,207.00",0.0347,Buy,17,12,5,0,0,Buy
...,...,...,...,...,...,...,...,...,...,...,...,...
96,Unilever,ULVR,Personal Goods,"5,151.00",0.0029,Buy,16,6,6,2,1,Overweight
97,United Utilities,UU.,"Gas, Water & Multi-utilities",808,0.0025,Buy,12,4,4,1,2,Overweight
98,Vodafone Group,VOD,Mobile Telecommunications,155.88,0.0203,Buy,20,14,3,1,0,Buy
99,Whitbread,WTB,Retail hospitality,"4,357.00",0.0035,Hold,22,3,12,3,3,Neutral
100,WPP plc,WPP,Media,970.6,0.0208,Hold,21,10,9,1,1,Overweight

In [12]:
# Mid-price (p) entries are strings and have commas. The commas will need removing before converting the string to a float
price_df = clean_df.copy()

price_df['Mid-price (p)'] = price_df['Mid-price (p)'].str.replace(',','')

price_df['Mid-price (p)'] = price_df['Mid-price (p)'].astype(float)

price_df.head()

,Company,Ticker,Sector,Mid-price (p),Change,Our view,Brokers,Buy,Neutral,Sell,Strong Sell,Recommendation
0,3i,III,Financial Services,1099.5,0.0171,Hold,5,4,1,0,0,Buy
1,Admiral Group,ADM,Nonlife Insurance,2115.0,-0.42%,Hold,18,2,6,7,3,Underweight
2,Anglo American plc,AAL,Mining,1744.0,0.0154,Hold,24,15,6,2,0,Buy
3,Antofagasta,ANTO,Mining,848.2,0.0326,Hold,21,8,9,3,0,Overweight
4,Ashtead Group,AHT,Support Services,2207.0,0.0347,Buy,17,12,5,0,0,Buy

In [13]:
# the Change column entries are strings, but also the positive values need to be multiplied to 100, 
# and the negative values need the % symbol removed, before converting into floats
# the function below will make these changes
def format_change(string):
    if string.endswith('%'):
            stringy = string.replace('%', '')
            floater = float(stringy)           
            if floater >=0:
                floater2 = floater*100
                return floater2
            return floater
    else:
        stringy = float(string)
        if stringy>=0:
            stringy2 = stringy*100
            return stringy2
        return stringy

In [14]:
# a new column can now be made, the entries of which are calculated from the Change column entries run through the format_change function
change_df = price_df.copy()

change_df['Change (%)'] = change_df['Change'].map(format_change)
change_df.head(16)

,Company,Ticker,Sector,Mid-price (p),Change,Our view,Brokers,Buy,Neutral,Sell,Strong Sell,Recommendation,Change (%)
0,3i,III,Financial Services,1099.50,0.0171,Hold,5,4,1,0,0,Buy,1.71
1,Admiral Group,ADM,Nonlife Insurance,2115.00,-0.42%,Hold,18,2,6,7,3,Underweight,-0.42
2,Anglo American plc,AAL,Mining,1744.00,0.0154,Hold,24,15,6,2,0,Buy,1.54
3,Antofagasta,ANTO,Mining,848.20,0.0326,Hold,21,8,9,3,0,Overweight,3.26
4,Ashtead Group,AHT,Support Services,2207.00,0.0347,Buy,17,12,5,0,0,Buy,3.47
5,Associated British Foods,ABF,Food Producers,2260.00,0.00,Hold,20,13,5,1,0,Buy,0.00
6,AstraZeneca,AZN,Pharmaceuticals & Biotechnology,7368.00,0.014,Buy,25,16,5,2,2,Buy,1.40
7,Auto Trader Group,AUTO,Media,523.80,-0.42%,Hold,19,4,11,4,0,Neutral,-0.42
8,Aveva,AVV,Software & Computer Services,3698.00,-0.38%,Hold,15,5,7,2,0,Overweight,-0.38
9,Aviva,AV.,Life Insurance,356.40,0.0082,Buy,17,12,4,0,0,Buy,0.82
10,BAE Systems,BA.,Aerospace & Defence,544.20,0.0138,Buy,19,9,10,0,0,Overweight,1.38
11,Barclays,BARC,Banks,137.58,0.0104,Hold,18,8,6,2,0,Overweight,1.04
12,Barratt Developments,BDEV,Household Goods & Home Construction,629.00,0.0064,Hold,13,7,3,2,0,Overweight,0.64
13,Berkeley Group Holdings,BKG,Household Goods & Home Construction,2870.50,0.0143,Hold,12,3,5,3,0,Neutral,1.43
14,BHP,BHP,Mining,3865.00,0.0238,Hold,23,3,16,2,2,Neutral,2.38
15,BP,BP.,Oil & Gas Producers,1733.00,0.0123,Buy,29,15,9,0,1,Buy,1.23

In [15]:
# next, i will use the following info
holding = ('BP.', 500, 1535.21)

print(holding[0]) # company ticker
print(holding[1]) # number of shares
print(holding[2]) # price paid

BP.
500
1535.21

In [16]:
#  a new dictionary, that uses the above information and returns the holding cost, holding value and percent change in value
holding_dict = {'holding_cost' : holding[1]*(holding[2])/100,
               'holding_value' : holding[1]*(change_df.loc[change_df['Ticker']==holding[0]]['Mid-price (p)'].mean())/100,
               'change_in_value' : (((change_df.loc[change_df['Ticker']==holding[0]]['Mid-price (p)'].mean())-(holding[2]))/holding[2])*100}

In [17]:
holding_dict

{'holding_cost': 7676.05,
 'holding_value': 8665.0,
 'change_in_value': 12.883579445157336}

In [19]:
# next, two new columns are created:
#Beat Market gives True or False to whether a stock's change % is better than the market average
#Buy Ratio gives the ratio of Buy vs Brokers
comparison_df = change_df.copy()

comparison_df['Beat Market'] = comparison_df['Change (%)'] > comparison_df['Change (%)'].mean()
comparison_df['Buy Ratio'] = comparison_df['Buy']/comparison_df['Brokers']
comparison_df.head()

,Company,Ticker,Sector,Mid-price (p),Change,Our view,Brokers,Buy,Neutral,Sell,Strong Sell,Recommendation,Change (%),Beat Market,Buy Ratio
0,3i,III,Financial Services,1099.5,0.0171,Hold,5,4,1,0,0,Buy,1.71,True,0.800000
1,Admiral Group,ADM,Nonlife Insurance,2115.0,-0.42%,Hold,18,2,6,7,3,Underweight,-0.42,False,0.111111
2,Anglo American plc,AAL,Mining,1744.0,0.0154,Hold,24,15,6,2,0,Buy,1.54,True,0.625000
3,Antofagasta,ANTO,Mining,848.2,0.0326,Hold,21,8,9,3,0,Overweight,3.26,True,0.380952
4,Ashtead Group,AHT,Support Services,2207.0,0.0347,Buy,17,12,5,0,0,Buy,3.47,True,0.705882

In [20]:
# a watch list of companies is created, along with their target stock price
watchlist = [('TUI', 820.0), ('Whitbread', 4300.0), ('AstraZeneca', 7500.0), 
             ('Standard Chartered', 920.0), ('Barclays', 135.5)]
watchlist

[('TUI', 820.0),
 ('Whitbread', 4300.0),
 ('AstraZeneca', 7500.0),
 ('Standard Chartered', 920.0),
 ('Barclays', 135.5)]

In [21]:
# a companies list is produced from the watch list, identifying any companies:
# whose stock price is equal to or higher than the target price
# whose Buy Ratio is 0.5 or greater
companies_list = []
for company, target in watchlist:    
    priceval = comparison_df.loc[comparison_df['Company']==company]['Mid-price (p)'].values[0]
    if target >= priceval or comparison_df.loc[comparison_df['Company']==company]['Buy Ratio'].values[0]>=0.5:
        companies_list.append(company)
companies_list

['TUI', 'AstraZeneca', 'Standard Chartered']